### ISSUE TITLE
can't install ZIP

### ISSUE THREAD

**Issue by mmokross** [mrmadhav/Evolus-Pencil-HTML-Export-Template#1]
I tried the installation described in https://github.com/mrmadhav/Evolus-Pencil-HTML-Export-Template/wiki

I downloaded https://github.com/mrmadhav/Evolus-Pencil-HTML-Export-Template/archive/master.zip and tried to "manage export templates" and add the ZIP, but got a error dialog "error installing template".

What to do?

Running Pencil 2.0.5 on Windows 7.
Thanks, Michael

**Comment by mrmadhav** [comment]
Hi Michael,

It seems that Github actually puts the contents inside a directory in the zip file. This is the reason why the installation fails.

I have now created a 'bin' directory in the repository, just download a new copy of the code, extract it manually and then navigate to the 'bin' directory. You can install the Zip file you find there using pencil.

Do let me know how it goes. I'll update the instructions on the wiki also.

Best Regards,
Madhav

**Comment by mmokross** [comment]
Thanks! :-)
