### ISSUE TITLE
Exporting freeze

### ISSUE THREAD

**Issue by fredcido** [mrmadhav/Evolus-Pencil-HTML-Export-Template#2]
I'm having a problem with Export to pages. It freezes once it shows "Exporting documents..."
Do you have any idea what is the reason?

![screenshot from 2015-07-13 14 42 07](https://cloud.githubusercontent.com/assets/7162412/8643328/62ce24c8-296d-11e5-9919-533be26f5a63.png)

**Comment by mrmadhav** [comment]
Hi,

I am not sure if it is the template that is causing the freeze, I will need to do testing to be able to reproduce. Can you give me more details about the version of Pencil you are using (Pencil Version, OS Version etc...) ?

Best Regards,
Madhav

**Comment by fredcido** [comment]
I've just figured out the problem. Some issue with firefox plugin, it's not the template. Sorry for the incovenience. Found the solution here: http://thegeekettespeaketh.com/2013/03/solved-cant-export-png-from-evolus-pencil/

**Comment by mrmadhav** [comment]
Ok, glad to see the issue is resolved for you. Thanks for your contribution.
